using System;
using ThermoFisher.CommonCore.Data.Business;

namespace ThermoFisher.CommonCore.Data.Interfaces;

/// <summary>
/// General interface to regression calculations (calibration curves)
/// Specific instances of this can be generated by using the factory: Calibration.CreateCalibrationCurve
/// </summary>
public interface IRegression : ICloneable
{
	/// <summary>
	/// Gets a statistical result from a regression calculation.
	/// For curves not supporting this, return -1
	/// </summary>
	double RSquared { get; }

	/// <summary>
	/// Gets the calibration equation (such as "y=mx+c")
	/// </summary>
	string Equation { get; }

	/// <summary>
	/// Gets a value indicating whether this regression is fitted correctly.
	/// After constructing a calibration object, it can only be used if "Ok".
	/// For example: if there are no calibration levels, Ok will be false.
	/// </summary>
	bool Ok { get; }

	/// <summary>
	/// Gets the highest X value on the calibration curve
	/// </summary>
	double MaxXValue { get; }

	/// <summary>
	/// Gets the highest Y value on the calibration curve
	/// </summary>
	double MaxYValue { get; }

	/// <summary>
	/// Find the predicted amount given a response ratio
	/// </summary>
	/// <param name="responseRatio">The response ratio of the peak being measured</param>
	/// <returns>The calculated amount for this response ratio</returns>
	double PredictedAmount(double responseRatio);

	/// <summary>
	/// Find the response ratio which represents a calculated amount.
	/// This is the inverse of the calculation needed for quantitation.
	/// </summary>
	/// <param name="amount">The known amount</param>
	/// <returns>The response ratio which would represent this amount</returns>
	double PredictedResponseRatio(double amount);

	/// <summary>
	/// Create a table of data to plot on a calibration curve
	/// </summary>
	/// <param name="requiredPoints">The number of calibration curve points to supply</param>
	/// <param name="useMaxValue">If useMaxValue is true, plotting is performed between 0 and the
	/// larger of the base amount of the largest level and maxValue.</param>
	/// <param name="maxValue">Maximum value for the curve (if useMaxValue is set)</param>
	/// <returns>The generated curve data, or null if there are insufficient required points specified</returns>
	CalibrationCurvePoint[] PreparePlotData(int requiredPoints, bool useMaxValue, double maxValue);
}
